# SConscript

Import('env Automatic_Program Automatic_Library')
#env=env.Copy(USE_BOOST_SERIALIZATION=1)
#Automatic_Program(env,"deformable_interface",["main.cpp","DEFORMABLE_EXAMPLE.cpp"])
#Automatic_Program(env,"dump_geometry",["dump_geometry.cpp"])

### automatic generation of library targets
#Automatic_Library(env,"PhysBAM_Wrapper",[],[],[],["libmain.cpp","DEFORMABLE_EXAMPLE.cpp"],False,True,False,True)
Automatic_Program(env,"xx",["main.cpp"])

