# SConscript

Import('env Automatic_Program')
env=env.Copy(USE_DYNAMICS=1)
Automatic_Program(env,"bpp",["main.cpp","PARTITIONED_DRIVER.cpp",
                              "SOLID_SOLVER_PB.cpp","FLUID_SOLVER_PB.cpp"])
