# SConscript

Import('env Automatic_Program')
env=env.Copy(USE_GEOMETRY=1)
env.Append(LIBS=["colamd"]);
Automatic_Program(env,"micro",["main.cpp","PARSE_DATA.cpp","FLUID_LAYOUT.cpp",
                               "CACHED_ELIMINATION_MATRIX.cpp",
                               "FLAT_SYSTEM.cpp","FREQUENCY_TRACKER.cpp",
                               "JOB_SCHEDULER.cpp",
                               "FLUID_LAYOUT_FEM.cpp","PARSE_DATA_FEM.cpp","FLAT_SYSTEM_FEM.cpp",
                               "FEM_MESHING_TESTS.cpp"])
