# SConscript

Import('env Automatic_Program')
env=env.Copy(USE_GEOMETRY=1)
env.Append(LIBS=["colamd"]);
Automatic_Program(env,"micro",["main.cpp","PARSE_DATA.cpp","FLUID_LAYOUT.cpp",
                               "CACHED_ELIMINATION_MATRIX.cpp",
                               "FLAT_SYSTEM.cpp"])
