# SConscript

Import('env Automatic_Program')
env=env.Copy(USE_GEOMETRY=1)
env.Append(LIBS=["colamd"]);
Automatic_Program(env,"micro",["main.cpp","PARSE_DATA.cpp","FLUID_LAYOUT.cpp",
                               "CACHED_ELIMINATION_MATRIX.cpp",
                               "FLAT_SYSTEM.cpp","FREQUENCY_TRACKER.cpp",
                               "JOB_SCHEDULER.cpp",
                               "FLUID_LAYOUT_FEM.cpp","FLUID_LAYOUT_FEM_EXTRUDED.cpp",
                               "PARSE_DATA_FEM.cpp",
                               "FLAT_SYSTEM_FEM.cpp","FLAT_SYSTEM_FEM_EXTRUDED.cpp",
                               "FEM_MESHING_TESTS.cpp","FEM_TABLE.cpp"])
Automatic_Program(env,"fem",["main-fem.cpp","CACHED_ELIMINATION_MATRIX.cpp",
                               "FLAT_SYSTEM.cpp","FREQUENCY_TRACKER.cpp",
                               "JOB_SCHEDULER.cpp","COMPONENT_LAYOUT_FEM.cpp",
                               "COMPONENT_PIPE.cpp","COMPONENT_CHANGE.cpp",
                               "COMPONENT_BC.cpp","COMPONENT_JOINT.cpp"])
