# SConscript

Import('env Automatic_Program')
env=env.Copy(USE_HYBRID=1,USE_FFTW=1)
Automatic_Program(env,"fourier_apic",["main.cpp"])
Automatic_Program(env,"fourier_mac",["main-mac.cpp"])
env.Append(LIBS='lapack')
Automatic_Program(env,"fourier_mac_p",["main-mac-p.cpp","COMPLEX_EIGENVALUES.cpp"])
Automatic_Program(env,"region-vort",["region-vort.cpp"])
Automatic_Program(env,"test-xfers",["test-xfers.cpp"])
