# SConscript

import os
Import('env Automatic_Program')

if 'BOOST_ROOT' in os.environ:

    env = env.Copy()

    env.Append( LIBS = [
        'lapack', 'blas'
    ] )

    sources = [
        'main.cpp',
        'PLS_FSI_DRIVER.cpp',
        'PLS_FSI_EXAMPLE.cpp',
        'SURFACE_TENSION.cpp'
    ]

    if 'PETSC_DIR' in os.environ:
        env.Append( LIBPATH = [
            os.environ['PETSC_DIR'] + '/' + os.environ['PETSC_ARCH'] + '/lib'
        ] )
        env.Append( LIBS = [
            'petsc'
        ] )
        sources.extend( [
            '../Petsc/Print_KSP_Info.cpp',
            '../Petsc/Solve_SPD_System_With_ICC_PCG.cpp'
        ] )

    Automatic_Program( env, "two_phase_flow_2d_test", sources )
