# SConscript

Import('env Automatic_Program')
env=env.Copy(USE_DYNAMICS=1)
env=env.Copy(USE_HYBRID=1)
Automatic_Program(env,"smoke",["SMOKE_DRIVER.cpp","SMOKE_EXAMPLE.cpp","SMOKE_PARTICLES.cpp","main.cpp"])

