# SConscript

Import('env Automatic_Program')
env=env.Copy(USE_TOOLS=1)
Automatic_Program(env,"auto_diff",["main.cpp","TEST_HELPER_10.cpp","TEST_HELPER_11.cpp","TEST_HELPER_12.cpp","TEST_HELPER_13.cpp","TEST_HELPER_14.cpp","TEST_HELPER_15.cpp","TEST_HELPER_16.cpp","TEST_HELPER_17.cpp","TEST_HELPER_18.cpp","TEST_HELPER_19.cpp","TEST_HELPER_1.cpp","TEST_HELPER_20.cpp","TEST_HELPER_21.cpp","TEST_HELPER_22.cpp","TEST_HELPER_23.cpp","TEST_HELPER_24.cpp","TEST_HELPER_25.cpp","TEST_HELPER_26.cpp","TEST_HELPER_27.cpp","TEST_HELPER_28.cpp","TEST_HELPER_29.cpp","TEST_HELPER_2.cpp","TEST_HELPER_3.cpp","TEST_HELPER_4.cpp","TEST_HELPER_5.cpp","TEST_HELPER_6.cpp","TEST_HELPER_7.cpp","TEST_HELPER_8.cpp","TEST_HELPER_9.cpp"])
