# SConscript

Import('env Automatic_Program')
env=env.Copy(USE_DYNAMICS=1)
Automatic_Program(env)

#Automatic_Program(env,'Burning_Paper/render_preprocess')
#Automatic_Program(env,'Burning_Paper/adjust_temperature_16')
#Automatic_Program(env,'Burning_Paper/animate_translation_16')
