# SConscript

Import('env Automatic_Program')
Automatic_Program(env,"mpm_2d",["main_2d.cpp","MPM_CONSTITUTIVE_MODEL.cpp","MPM_PARTICLES.cpp","MPM_CUBIC_B_SPLINE.cpp","MPM_SIMULATION.cpp","MPM_SYSTEM.cpp","MPM_VECTOR.cpp","SURFACE_RECONSTRUCTION_ANISOTROPIC_KERNAL.cpp","MPM_SURFACE_2D.cpp"])
Automatic_Program(env,"mpm_3d",["main_3d.cpp","MPM_CONSTITUTIVE_MODEL.cpp","MPM_PARTICLES.cpp","MPM_CUBIC_B_SPLINE.cpp","MPM_SIMULATION.cpp","MPM_SYSTEM.cpp","MPM_VECTOR.cpp","SURFACE_RECONSTRUCTION_ANISOTROPIC_KERNAL.cpp"])
