#!/usr/bin/python

import sys
from physbam import *

T=float
TV=Vf2
stream_type="float"

### hard coded parameters
multiplier=400
linewidth=5/multiplier
styles=["stroke"]
clip=BOX_Vf2(0,1,0,1)
border=False
#styles=[".8 setgray fill","[.2 .2] 0 setdash stroke","[1 .5 .2 .5] 0 setdash stroke","[1] 0 setdash stroke","stroke"]

def Header(grid):
    print "%!PS-Adobe-3.0 EPSF-3.0"
    domain=grid.Domain()
    if clip: domain=clip
    img_box=(domain*multiplier).Thickened(2)
    print "%%BoundingBox: "+"%s %s"%(img_box.Minimum_Corner(),img_box.Maximum_Corner())
    print "gsave"
    print "%g %g scale"%(multiplier,multiplier)
    if border:
        print "newpath"
        print "  %g %g moveto"%(grid.xmin,grid.ymin)
        print "  %g %g lineto"%(grid.xmax,grid.ymin)
        print "  %g %g lineto"%(grid.xmax,grid.ymax)
        print "  %g %g lineto"%(grid.xmin,grid.ymax)
        print "  closepath"
        print "  %g setlinewidth"%linewidth
        print "stroke"

def Footer():
    print "grestore"

def Levelset(curve,num):
    particles=curve.particles
    curve.mesh.Initialize_Ordered_Loop_Nodes()
    print "\ngsave"
    print "newpath"
    for nodes in curve.mesh.ordered_loop_nodes:
        print "   %s moveto"%particles.X[nodes[1]]
        for n in nodes[2:]: print "   %s lineto"%particles.X[n]
    print " closepath %s setlinewidth %s"%(linewidth,styles[num-1])
    print "grestore\n"

for n in range(1,len(sys.argv)):
    levelset=LEVELSET_UNIFORM_Vf2(GRID_Vf2(),ARRAYS_2D_f())
    Read_From_File(stream_type,sys.argv[n],levelset)
    if n==1: Header(levelset.grid)
    curve=DUALCONTOUR_UNIFORM_Vf2.Create_Segmented_Curve_From_Levelset(levelset)
    Levelset(curve,n)
Footer()
