# SConscript
Import('env Automatic_Program Automatic_Library')

Automatic_Program(env,"test_bed",["test_bed.cpp","APPLY_VISCOSITY.cpp","SOURCE_VELOCITY_CURVE.cpp","ACCURACY_INFO.cpp","PROJECT_INCOMPRESSIBILITY.cpp",
                                  "PROJECT_INCOMPRESSIBILITY_GIBOU.cpp","POISSON_PROJECTION_SYSTEM.cpp","MISC_UTILITIES.cpp","BOUNDARY_CONDITIONS_BOX.cpp",
                                  "BOUNDARY_CONDITIONS_GIBOU_ANALYTIC_ONE.cpp","BOUNDARY_CONDITIONS.cpp","BOUNDARY_CONDITIONS_CIRCLE.cpp","TEST_COMMON.cpp",
                                  "SIM_COMMON.cpp","OBJECTS_COMMON.cpp","PARAMETERS_COMMON.cpp","PROJECT_INCOMPRESSIBILITY_SLIP.cpp"])
# Automatic_Program(env,"test_bed1",["test_bed1.cpp","APPLY_VISCOSITY.cpp","SOURCE_VELOCITY_CURVE.cpp","ACCURACY_INFO.cpp","PROJECT_INCOMPRESSIBILITY.cpp",
#                                   "PROJECT_INCOMPRESSIBILITY_GIBOU.cpp","POISSON_PROJECTION_SYSTEM.cpp","MISC_UTILITIES.cpp","BOUNDARY_CONDITIONS_SEGMENT.cpp",
#                                    "BOUNDARY_CONDITIONS.cpp","TEST_COMMON.cpp","SIM_COMMON.cpp","OBJECTS_COMMON.cpp","PARAMETERS_COMMON.cpp"])
Automatic_Program(env,"boundary_conditions_2d",["main.cpp"])
Automatic_Program(env,"extrapolation_test",["extrapolation_test.cpp"])
Automatic_Program(env,"projection",["projection.cpp","POISSON_PROJECTION_SYSTEM.cpp"])

