local_env=Environment();

local_env.Append(CXXFLAGS=['-I/usr/local/include', '-g'])
local_env.Append(LINKFLAGS=['-L/usr/local/lib'])
local_env.Append(LIBS=['boost_program_options','rt'])

program=local_env.Program("master",["master.cpp"])
program=local_env.Program("slave",["slave.cpp"])

