# SConscript

Import('env Automatic_Program')
Automatic_Program(env,"compressible_thin_shells_2d",['main.cpp','Strawman_Example/STRAWMAN_DRIVER.cpp'])
Automatic_Program(env,"to_gnuplot",['to_gnuplot.cpp'])
