# SConscript

Import('env Automatic_Program')

Automatic_Program(env,"testing",["main.cpp", "MARCHING_TETRAHEDRA_CUTTING.cpp"])
Automatic_Program(env,"testing3",["main3.cpp", "MARCHING_TETRAHEDRA_CUTTING.cpp"])
