# SConscript

Import('env Automatic_Program')
env=env.Copy(USE_PTHREADS=1)
env.Append(CXXFLAGS="-DUSE_PTHREADS")
Automatic_Program(env,"refinement_pls",["main.cpp","Water_Tests/REFINEMENT_THREADS.cpp"])

