# SConscript

Import('env Automatic_Program')
env=env.Copy(USE_DYNAMICS=1)
Automatic_Program(env,"fluids_color_2d",["main.cpp"])
Automatic_Program(env,"conv",["conv.cpp"])
Automatic_Program(env,"draw_bubble",["draw_bubble.cpp"])

