# SConscript

Import('env Automatic_Program')
Automatic_Program(env,"fluids_color_2d",["main.cpp"])
Automatic_Program(env,"conv",["conv.cpp"])
Automatic_Program(env,"draw_bubble",["draw_bubble.cpp"])

