# SConscript

Import('env Automatic_Program')
env=env.Copy(USE_SOLIDS=1)
Automatic_Program(env,"solids_3d",["Hair_Sim_Tests/HAIR_SIM_TESTS.cpp","Hair_Sim_Tests/HAIR_STRAND_TESTS.cpp","Mass_Weighted_Self_Collisions/MASS_WEIGHTED_SELF_COLLISIONS.cpp","main.cpp"])
#Automatic_Program(env,'Incompressible/fragment_volumes')

