# SConscript

Import('env Automatic_Program')
env=env.Copy(USE_GEOMETRY=1)
Automatic_Program(env,"align_bone",["main.cpp"])
Automatic_Program(env,"align_bone2",["main2.cpp"])
Automatic_Program(env,"round",["two-round-parts.cpp"])
Automatic_Program(env,"align_bone_start",["align_bone_start.cpp"])
