# SConscript
import os
Import('env Automatic_Program')
env=env.Copy(USE_HYBRID=1)

if os.environ.has_key('PARTIO'):
    partio_root=os.environ['PARTIO']
    env.Append(CPPPATH=[partio_root+'/include'])
    env.Append(LIBPATH=[partio_root+'/lib'])
    env.Append(LIBS=['partio'])
    Automatic_Program(env,"mpm2partio",["main.cpp"])
