# SConscript

import os
Import('env Automatic_Program')

if 'BOOST_ROOT' in os.environ:

    env = env.Copy()

    env.Append( LIBPATH = [
        os.environ['BOOST_ROOT'] + '/lib'
    ] )
    env.Append( RPATH = [
        os.environ['BOOST_ROOT'] + '/lib'
    ] )
    env.Append( LIBS = [
        'boost_program_options',
        'boost_thread',
        'X11', 'lapack', 'blas'
    ] )

    sources = [
        'Build_And_Solve_Dirichlet_System.cpp',
        'Build_And_Solve_Interface_System.cpp',
        'Build_And_Solve_Neumann_System.cpp',
        'Build_Dirichlet_System.cpp',
        'Build_Interface_System.cpp',
        'Build_Neumann_System.cpp',
        'Coarsen_Embedding.cpp',
        'DOMAIN_EMBEDDING_CUBE_SUBSYS.cpp',
        'DOMAIN_EMBEDDING_UNSTRUCTURED_SUBSYS.cpp',
        'DOMAIN_REGULAR_CROSS_SUBSYS.cpp',
        'Eval_Phi_Over_Fine_Grid.cpp',
        'Lagrangify_Level_Set.cpp',
        'main.cpp',
        'Main_Examples.cpp',
        'main_impl.cpp',
        'Parsing/Parse_Command_Line.cpp',
        'Parsing/Parse_String_Example.cpp',
        'Parsing/Parse_String_Grid_BC.cpp',
        'Parsing/Parse_String_Grid_Box.cpp',
        'Parsing/Parse_String_Level_Set.cpp',
        'Parsing/Parse_String_N_Cell.cpp',
        'Parsing/Parse_String_Solver.cpp',
        'Parsing/Print_Help.cpp'
    ]

    if 'PETSC_DIR' in os.environ:
        env.Append( LIBPATH = [
            os.environ['PETSC_DIR'] + '/' + os.environ['PETSC_ARCH'] + '/lib'
        ] )
        env.Append( LIBS = [
            'petsc'
        ] )
        sources.extend( [
            '../Petsc/Print_KSP_Info.cpp',
            '../Petsc/Solve_SPD_System_With_ICC_PCG.cpp'
        ] )

    Automatic_Program( env, 'multigrid_embedded_poisson', sources )
