# SConscript

Import('env Automatic_Program')
Automatic_Program(env)

Automatic_Program(env,'River/grow_river_height')
Automatic_Program(env,'River/prefix_union')
Automatic_Program(env,'River/clean_river')
