# SConscript

Import('env Automatic_Program')
env=env.Copy(USE_DEFORMABLES=1)
env.Append(CXXFLAGS=["-I/home/craig/narain/deps/include/","-Wno-unused-but-set-variable"])
Automatic_Program(env,"converter",["main.cpp"])
