# SConscript

Import('env Automatic_Program')
env=env.Copy(USE_SOLIDS=1)
env.Append(CPPPATH=["/home/craig/narain/deps/include/"])
env.Append(CXXFLAGS=["-Wno-unused-but-set-variable"])
env.Append(LIBPATH=["/home/craig/narain/deps/lib"])
env.Append(LIBS=["BulletCollision","BulletDynamics","BulletFileLoader","BulletSoftBody","BulletWorldImporter","LinearMath","ConvexDecomposition","OpenGLSupport","BulletCollision","BulletDynamics","BulletFileLoader","BulletSoftBody","BulletWorldImporter","LinearMath","ConvexDecomposition","OpenGLSupport"])
Automatic_Program(env,"converter",["main.cpp"])
