# SConscript

Import('env Automatic_Program')
# Automatic_Program(env,"articulation_editor",["articulation_editor.cpp","ARTICULATION_VISUALIZATION.cpp","OPENGL_COMPONENT_JOINT_3D.cpp","OPENGL_COMPONENT_MUSCLE_3D.cpp","TOOL.cpp"]) # doesn't compile
