# SConscript

Import('env Automatic_Program')
Automatic_Program(env,"integration_test",["main.cpp"])
Automatic_Program(env,"mc/view_case",["mc/view_case.cpp"])
Automatic_Program(env,"mc/view_levelset",["mc/view_levelset.cpp"])
Automatic_Program(env,"mc/primitive_integration",["mc/primitive_integration.cpp"])

