# SConscript

Import('env Automatic_Program')
# Automatic_Program(env,"c3d2motion",["c3d2motion.cpp","C3D_PARAMETER_VALUE.cpp","C3D_FILE.cpp"]) # doesn't compile
# Automatic_Program(env,"links2segments",["links2segments.cpp"])

