//#####################################################################
// Copyright 2009, Andrew Selle.
// This file is part of PhysBAM whose distribution is governed by the license contained in the accompanying file PHYSBAM_COPYRIGHT.txt.
//#####################################################################
#ifndef __FIRE_ADVECTION_POLICY__
#define __FIRE_ADVECTION_POLICY__

#include <Tools/Advection/ADVECTION_FORWARD.h>
#include <Tools/Grids_Uniform_Advection/ADVECTION_UNIFORM_FORWARD.h>
#include <Incompressible/Advection_Collidable/ADVECTION_COLLIDABLE_FORWARD.h>
#include <Incompressible/Advection_Collidable/Grids_Uniform_Advection_Collidable/ADVECTION_COLLIDABLE_UNIFORM_FORWARD.h>
#include <Incompressible/Interpolation_Collidable/INTERPOLATION_COLLIDABLE_POLICY.h>
#include <Dynamics/Advection_Equations/FIRE_ADVECTION_FORWARD.h>
#include <Dynamics/Interpolation/FIRE_INTERPOLATION_POLICY.h>

namespace PhysBAM{

template<class TV>
struct FIRE_ADVECTION_POLICY
{
private:
    typedef typename TV::SCALAR T;
public:
    // multiphase fire
    typedef ADVECTION_SEMI_LAGRANGIAN_UNIFORM<TV,T,typename FIRE_INTERPOLATION_POLICY<TV>::AVERAGING_FIRE_MULTIPHASE,typename FIRE_INTERPOLATION_POLICY<TV>::LINEAR_INTERPOLATION_FIRE_MULTIPHASE> ADVECTION_SEMI_LAGRANGIAN_FIRE_MULTIPHASE;
    typedef ADVECTION_WRAPPER_FIRE_MULTIPHASE_UNIFORM<TV,T,ADVECTION_SEMI_LAGRANGIAN_FIRE_MULTIPHASE> ADVECTION_WRAPPER_SEMI_LAGRANGIAN_FIRE_MULTIPHASE;
    // multiphase fire collidable
    typedef ADVECTION_SEMI_LAGRANGIAN_COLLIDABLE_FACE_UNIFORM<TV,typename FIRE_INTERPOLATION_POLICY<TV>::FACE_LOOKUP_FIRE_MULTIPHASE_COLLIDABLE> ADVECTION_SEMI_LAGRANGIAN_FIRE_MULTIPHASE_COLLIDABLE;
    typedef ADVECTION_WRAPPER_COLLIDABLE_FACE<TV,T,typename FIRE_INTERPOLATION_POLICY<TV>::FACE_LOOKUP_FIRE_MULTIPHASE,ADVECTION_SEMI_LAGRANGIAN_FIRE_MULTIPHASE_COLLIDABLE,FACE_LOOKUP_COLLIDABLE_UNIFORM<TV> > NESTED_ADVECTION_WRAPPER_SEMI_LAGRANGIAN_FIRE_MULTIPHASE_COLLIDABLE;
    typedef ADVECTION_WRAPPER_FIRE_MULTIPHASE_UNIFORM<TV,T,NESTED_ADVECTION_WRAPPER_SEMI_LAGRANGIAN_FIRE_MULTIPHASE_COLLIDABLE> ADVECTION_WRAPPER_SEMI_LAGRANGIAN_FIRE_MULTIPHASE_COLLIDABLE;
};
}
#endif
