//#####################################################################
// Copyright 2009, Andrew Selle.
// This file is part of PhysBAM whose distribution is governed by the license contained in the accompanying file PHYSBAM_COPYRIGHT.txt.
//#####################################################################
#ifndef __FIRE_ADVECTION_POLICY__
#define __FIRE_ADVECTION_POLICY__

#include <Grid_PDE/Advection/ADVECTION_FORWARD.h>
#include <Grid_PDE/Advection/ADVECTION_UNIFORM_FORWARD.h>
#include <Incompressible/Advection_Collidable/ADVECTION_COLLIDABLE_FORWARD.h>
#include <Incompressible/Advection_Collidable/Grids_Uniform_Advection_Collidable/ADVECTION_COLLIDABLE_UNIFORM_FORWARD.h>
#include <Dynamics/Advection_Equations/FIRE_ADVECTION_FORWARD.h>

namespace PhysBAM{

template<class TV> class FACE_LOOKUP_FIRE_MULTIPHASE_UNIFORM;

template<class TV>
struct FIRE_ADVECTION_POLICY
{
private:
    typedef typename TV::SCALAR T;
public:
    // multiphase fire
    typedef ADVECTION_SEMI_LAGRANGIAN_UNIFORM<TV,T,AVERAGING_UNIFORM<TV,FACE_LOOKUP_FIRE_MULTIPHASE_UNIFORM<TV> >,LINEAR_INTERPOLATION_UNIFORM<TV,T,FACE_LOOKUP_FIRE_MULTIPHASE_UNIFORM<TV> > > ADVECTION_SEMI_LAGRANGIAN_FIRE_MULTIPHASE;
    typedef ADVECTION_WRAPPER_FIRE_MULTIPHASE_UNIFORM<TV,T,ADVECTION_SEMI_LAGRANGIAN_FIRE_MULTIPHASE> ADVECTION_WRAPPER_SEMI_LAGRANGIAN_FIRE_MULTIPHASE;
    // multiphase fire collidable
    typedef ADVECTION_SEMI_LAGRANGIAN_COLLIDABLE_FACE_UNIFORM<TV,FACE_LOOKUP_COLLIDABLE_UNIFORM<TV,FACE_LOOKUP_FIRE_MULTIPHASE_UNIFORM<TV> > > ADVECTION_SEMI_LAGRANGIAN_FIRE_MULTIPHASE_COLLIDABLE;
    typedef ADVECTION_WRAPPER_COLLIDABLE_FACE<TV,T,FACE_LOOKUP_FIRE_MULTIPHASE_UNIFORM<TV>,ADVECTION_SEMI_LAGRANGIAN_FIRE_MULTIPHASE_COLLIDABLE,FACE_LOOKUP_COLLIDABLE_UNIFORM<TV> > NESTED_ADVECTION_WRAPPER_SEMI_LAGRANGIAN_FIRE_MULTIPHASE_COLLIDABLE;
    typedef ADVECTION_WRAPPER_FIRE_MULTIPHASE_UNIFORM<TV,T,NESTED_ADVECTION_WRAPPER_SEMI_LAGRANGIAN_FIRE_MULTIPHASE_COLLIDABLE> ADVECTION_WRAPPER_SEMI_LAGRANGIAN_FIRE_MULTIPHASE_COLLIDABLE;
};
}
#endif
