# SConscript

Import('env Automatic_Program')
env=env.Copy(USE_HYBRID=1,USE_OPENGL=1)
Automatic_Program(env,"mpm_mac",["main.cpp","STANDARD_TESTS_BASE.cpp","STANDARD_TESTS_2D.cpp","STANDARD_TESTS_3D.cpp"])
Automatic_Program(env,"dump_vort",["dump_vort.cpp"])
