# SConscript

import os
Import('env Automatic_Program Automatic_Library variant_build')

env=env.Copy()
env.Append(CPPPATH='.')

# generate library
#aero_interface_dso=Automatic_Library(env,'Aero_Interface',dirs=[],sources=['AERO_INTERFACE_1.cpp','PHYSBAM_INTERFACE.cpp'])
#env.Append(LIBS=[aero_interface_dso])

#Automatic_Program(env)

Automatic_Program(env,"Charbel",["main.cpp",'PHYSBAM_INTERFACE.cpp'])
Automatic_Program(env,"conversion_test",["conversion_test.cpp"])
